# Here we will discuss useful platforms 

github: # Replace with up to 4 GitHub Sponsors-enabled fubay18 e.g., [user1, user2]
patreon: # Replace with a single Patreon farikh
open_collective: # Replace with a single Open Collective dubay
ko_fi: # Replace with a single Ko-fi dubay
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., master/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., fornd-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., dubay_foundr
custom: # Replace with up to 4 custom sponsorship URLs e.g., [ https://instagram.com/lhitay12?igshid=ZDdkNTZiNTM=', 'https://x.com/fariekh23?t=lzO-Fn7BLMELZO51taFThw&s=09']
